apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gh2ug05p9-go
  janus-idp.io/tekton: gh2ug05p9-go
  backstage.io/kubernetes-id: gh2ug05p9-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gh2ug05p9-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
